export type PortalTheme = {
  id: string;
  tenant_id: string;
  name: string;
  code: string;
  is_default: boolean;
  logo_url: string | null;
  favicon_url: string | null;
  login_bg_url: string | null;
  primary_color: string;
  secondary_color: string;
  accent_color: string;
  header_bg: string;
  sidebar_bg: string;
  card_bg: string;
  text_color: string;
  muted_text_color: string;
  border_color: string;
  font_family: string;
  border_radius: string;
  custom_css: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

export type PortalDomain = {
  id: string;
  tenant_id: string;
  theme_id: string | null;
  domain: string;
  subdomain: string | null;
  host_type: "custom" | "subdomain" | "internal";
  is_primary: boolean;
  is_verified: boolean;
  verification_token: string | null;
  ssl_status: "pending" | "active" | "failed";
  login_title: string | null;
  login_subtitle: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

export type AgentPortalSetting = {
  id: string;
  tenant_id: string;
  agent_id: string;
  portal_name: string;
  portal_slug: string;
  theme_id: string | null;
  domain_id: string | null;
  show_transport: boolean;
  show_hotels: boolean;
  show_packages: boolean;
  show_ledger: boolean;
  show_invoices: boolean;
  show_reports: boolean;
  can_view_only_own_data: boolean;
  can_book_transport: boolean;
  can_book_hotels: boolean;
  can_book_packages: boolean;
  logo_url: string | null;
  welcome_text: string | null;
  support_phone: string | null;
  support_whatsapp: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};